eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
info:
  application:
    name: ${spring.application.name}
    description: Login Microservice
    version: '@project.version@'
    spring-cloud-version: '@spring.cloud-version@'