eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
info:
  application:
    name: ${spring.application.name}
    description: Sign up Microservice
    version: '0.0.1-SNAPSHOT'
    spring-cloud-version: '2021.0.3'